SAMPLES:
 - 20221128_K562_Actd_0h_rep1 # identical total RNA
 - 20221128_K562_Actd_0h_rep2
 - 20221128_K562_Actd_3h_rep1
 - 20221128_K562_Actd_3h_rep2
 - 20221128_K562_Actd_6h_rep1
 - 20221128_K562_Actd_6h_rep2

SPECIES:
 - human
 - fly

THREADS: 12

RIBO_BOWTIE2_INDEX: /home/chenzonggui/species/homo_sapiens/ncbi/bt2_rrna_index

HUMAN_FASTA: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/GRCh38.primary_assembly.genome.fa
HUMAN_GTF: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/gencode.v39.annotation.sorted.gtf
HUMAN_TRANSCRIPT_BED: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/gencode.v39.annotation.transcripts.bed.gz
HUMAN_ANNOTATION_TSV: /home/chenzonggui/species/homo_sapiens/GRCh38.p13/gencode.v39.annotation.tsv
HUMAN_SEQNAME_PATTERN: ^chr([0-9]+|[XY])$

FLY_FASTA: /home/chenzonggui/species/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.32.dna_sm.toplevel.fa
FLY_GTF: /home/chenzonggui/species/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.32.108.gtf
FLY_TRANSCRIPT_BED: /home/chenzonggui/species/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.32.108.transcripts.bed.gz
FLY_ANNOTATION_TSV: /home/chenzonggui/species/drosophila_melanogaster/Drosophila_melanogaster.BDGP6.32.108.annotation.tsv
FLY_SEQNAME_PATTERN: ^(2L|2R|3L|3R|[4XY])$